services:
  app:
    image: abrasel_people_crud-app:latest
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: people_app
    volumes:
      - ./person_crud:/workspace:cached
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1

  mysql:
    image: mysql:8.0
    container_name: people_mysql
    restart: always
    environment:
      MYSQL_DATABASE: people_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
